services:
  eggshell-postgresql:
    image: postgres:18-alpine
    container_name: eggshell-postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=eggshell-nest
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      eggshell-network:
        aliases:
          - localhost
          - 127.0.0.1

  # 添加 MongoDB 服务 (内存优化配置)
  eggshell-mongodb:
    image: mongo:8.0
    container_name: eggshell-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb123
    # volumes:
    #   - ../mongodb_data:/data/db
    command: >
      mongod
      --wiredTigerCacheSizeGB 0.25
      --syncdelay 60
      --slowms 10000
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      eggshell-network:
        aliases:
          - localhost
          - 127.0.0.1

networks:
  eggshell-network:
    external: true
    name: eggshell-network

# 单行命令docker run -d --name eggshell-postgresql -p 5432:5432 -e POSTGRESQL_USERNAME=postgres -e POSTGRESQL_PASSWORD=test123 -e POSTGRESQL_DATABASE=eggshell-nest -v ./postgresql:/bitnami/postgresql bitnami/postgresql:latest