services:
  eggshell-baiduMap-postgresql:
    image: bitnami/postgresql:latest
    container_name: eggshell-baiduMap-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=test123
      - POSTGRESQL_DATABASE=baidu-map-nest
    volumes:
      - ./postgresql_data:/bitnami/postgresql

networks:
  default:
    # name: eggshell-baiduMap-network
    driver: bridge

# 单行命令docker run -d --name eggshell-baiduMap-postgresql -p 5432:5432 -e POSTGRESQL_USERNAME=postgres -e POSTGRESQL_PASSWORD=test123 -e POSTGRESQL_DATABASE=baidu-map-nest -v ./postgresql:/bitnami/postgresql bitnami/postgresql:latest