include: docker-compose.yml

services:
  eggshell-server:
    image: bitnami/node:latest
    container_name: eggshell-server
    ports:
      - '7000:7000'
    environment:
      - NODE_ENV=production
    volumes:
      - ../apps/api/eggshell-nest/dist:/app/api/eggshell-nest/dist
      - ../apps/api/eggshell-nest/package.json:/app/api/eggshell-nest/package.json
      - ../apps/api/eggshell-nest/pnpm-lock.yaml:/app/api/eggshell-nest/pnpm-lock.yaml # 必须挂载lock文件
    depends_on:
      - eggshell-postgresql
    command: sh -c "npm install -g pnpm && pnpm install --prod && node dist/main.js"
