name: CI/CD Pipeline

on:
  push:
    branches: [main, master] # 只在 main 和 master 分支上触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 运行 Common Steps
      - name: Run Common Steps
        uses: ./.github/actions/common-steps
        with:
          ALIYUN_ACR_REGISTRY: ${{ secrets.ALIYUN_ACR_REGISTRY }}
          ALIYUN_ACR_USERNAME: ${{ secrets.ALIYUN_ACR_USERNAME }}
          ALIYUN_ACR_PASSWORD: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      # 后端测试
      - name: Backend Tests(后端测试)
        run: |
          cd apps/backend/baidu-map-nest
          pnpm install
          pnpm test

      # 前端测试
      # - name: Frontend Tests(前端测试)
      #   run: |
      #     cd apps/frontend/react-webpack
      #     pnpm install
      # pnpm test

      # 构建并推送后端镜像
      - name: Build and push backend image(构建并推送后端镜像)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/backend/baidu-map-nest/Dockerfile
          push: true
          # tags: ghcr.io/Magic-Jun-K/baidu-map-nest:latest
          tags: ${{ secrets.ALIYUN_ACR_REGISTRY }}/eggshell/baidu-map-nest:${{ github.sha }}

      # 构建并推送前端镜像
      - name: Build and push frontend image(构建并推送前端镜像)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/frontend/react-webpack/Dockerfile
          push: true
          # tags: ghcr.io/Magic-Jun-K/react-webpack:latest
          tags: ${{ secrets.ALIYUN_ACR_REGISTRY }}/eggshell/react-webpack:${{ github.sha }}
          # 添加构建参数，启用详细日志
          build-args: |
            NODE_ENV=production
            VERBOSE=true

      # 部署到服务器（使用 SSH）
      - name: Deploy to server(部署到服务器)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/eggshell

            # 或直接同步 compose 文件
            # docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_TOKEN }}

            # 登录阿里云 ACR
            docker login $ALIYUN_ACR_REGISTRY -u $ALIYUN_ACR_USERNAME -p $ALIYUN_ACR_PASSWORD

            # 拉取并启动容器
            docker-compose -f docker-compose.yml -f docker-compose.deploy.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
